### ISSUE TITLE
Atualização do README

### ISSUE THREAD

**Issue by gabrieljloh** [gabrieljloh/StoreStocker#1]
Atualizalção do README com informações do projeto.

**Comment by Arthu085** [comment]
Favor colocar o responsável dessa Issue para o @JeanPrei

**Comment by GabrielBoelter** [comment]
A partir de agora sou o responsável por essa issue.

**Comment by GabrielBoelter** [comment]
README estruturado, faltam apenas ajustes finais para finalizar.
